name: Testing
on:
  pull_request:
  push:
    branches:
      - develop
    
jobs:
  test:
    name: Running Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
            
      - name: Clang Install
        run:
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - &&
          sudo apt-get update &&
          sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-6.0 main" &&
          sudo apt-get install -y clang-6.0 lld-6.0

      - name: Run Tests
        run: mkdir -p tests/bin && mkdir -p tests/obj && make test
